server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hhhh
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 1000MB  # 最大支持文件大小
      max-request-size: 1000MB  # 最大支持请求大小
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
mybatis:
#  configuration:
  ##    map-underscore-to-camel-case: true
  ##    classpath:mybatis/*.xml,classpath:/mybatis-plus/*.xml
  mapper-locations: classpath:mapping/*.xml
#  configuration:
#    # 开启驼峰命名，MySQL的timestamp无法转化java中的Date可能就是这个属性没有开启
#    map-underscore-to-camel-case: true
mybatis-plus:
  mapper-locations: classpath:/mapping/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰命名，MySQL的timestamp无法转化java中的Date可能就是这个属性没有开启
#    map-underscore-to-camel-case: true


